// SPDX-FileCopyrightText: 2026 Ariazonaa
// SPDX-License-Identifier: MIT

using System.Globalization;

namespace Momentum4.App.Localization;

/// <summary>Sprache der Oberfläche.</summary>
public enum AppLanguage
{
    /// <summary>Nach der Windows-Anzeigesprache.</summary>
    Auto,
    German,
    English,
}

/// <summary>
/// Kleine, AOT-sichere Lokalisierung ohne <c>.resw</c>/PRI: zwei Wörterbücher (Deutsch/Englisch), zur Laufzeit über
/// den Schlüssel abgefragt. Die Sprache wird beim Start aus den Einstellungen gesetzt (<see cref="Init"/>); ein Wechsel
/// greift nach einem Neustart. XAML nutzt die Markup-Extension <see cref="Loc"/>, Code ruft <see cref="Get"/>.
/// </summary>
public static class L
{
    /// <summary>Ist die Oberfläche aktuell englisch?</summary>
    public static bool English { get; private set; }

    /// <summary>Setzt die Sprache. <c>Auto</c> = Englisch, außer die Windows-Anzeigesprache ist Deutsch.</summary>
    public static void Init(AppLanguage language)
    {
        English = language switch
        {
            AppLanguage.English => true,
            AppLanguage.German => false,
            _ => !CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("de", StringComparison.OrdinalIgnoreCase),
        };
    }

    /// <summary>Übersetzung zum Schlüssel; fehlt sie, kommt der Schlüssel selbst zurück (fällt im Test auf).</summary>
    public static string Get(string key) => (English ? En : De).TryGetValue(key, out var value) ? value : key;

    /// <summary>Wie <see cref="Get(string)"/>, aber mit <c>{0}</c>/<c>{1}</c>-Platzhaltern (invariante Formatierung).</summary>
    public static string Get(string key, params object?[] args) => string.Format(CultureInfo.InvariantCulture, Get(key), args);

    private static readonly Dictionary<string, string> De = new(StringComparer.Ordinal)
    {
        // Reiter / Abschnitte
        ["NoiseControl"] = "Noise Control",
        ["Equalizer"] = "Equalizer",
        ["Devices"] = "Geräte",
        ["Behavior"] = "Verhalten",
        ["Headset"] = "Headset",
        ["Firmware"] = "Firmware",
        ["SerialNumber"] = "Seriennummer",
        ["DeviceName"] = "Gerätename",
        ["PromptLanguageLabel"] = "Sprache der Ansagen",
        ["LastFullRead"] = "Zuletzt vollständig gelesen",
        // Noise Control / EQ
        ["AntiWind"] = "Anti-Wind",
        ["AncStrength"] = "ANC-Stärke",
        ["SoundMode"] = "Klangmodus",
        ["BassBoost"] = "Bass Boost",
        ["Preset"] = "Preset",
        ["AutoPauseTransparency"] = "Automatische Pause bei Transparenz",
        ["CustomCurvePlaceholder"] = "Eigene Kurve",
        ["CurveName"] = "Name für die aktuelle Kurve",
        ["SaveAsPreset"] = "Als eigenes Preset speichern",
        // Verhalten
        ["OnHead"] = "On-Head-Erkennung",
        ["SmartPause"] = "Smart Pause (beim Absetzen pausieren)",
        ["TouchControls"] = "Touch-Steuerung (Gesten am Hörer)",
        ["AutoAnswer"] = "Anrufe automatisch annehmen",
        ["ComfortCall"] = "Comfort Call",
        ["Prompts"] = "Töne & Sprachansagen",
        ["AutoPowerOff"] = "Automatisch ausschalten",
        // Noise Control (Code)
        ["ModeTransparency"] = "Transparenz",
        ["ModeAnc"] = "ANC",
        ["ModeAdaptive"] = "Adaptive",
        ["ModeOff"] = "Aus",
        ["AntiWindOff"] = "Aus",
        ["AntiWindMax"] = "Maximum",
        ["AntiWindAuto"] = "Automatisch",
        ["HintTransparency"] = "Umgebung hörbar (Transparent Hearing).",
        ["HintCustom"] = "Geräuschunterdrückung mit fester Stärke.",
        ["HintAdaptive"] = "Das Headset passt die Geräuschunterdrückung selbst an.",
        ["HintOff"] = "Keine Geräuschunterdrückung, nur passive Dämpfung.",
        ["ActNoiseControl"] = "Noise Control „{0}“",
        ["ActAntiWind"] = "Anti-Wind „{0}“",
        ["ActAutoPauseOn"] = "Automatische Pause an",
        ["ActAutoPauseOff"] = "Automatische Pause aus",
        ["ActAncStrength"] = "ANC-Stärke {0} %",
        // Status / Verbindung (Code)
        ["SearchingHeadset"] = "Suche MOMENTUM 4 …",
        ["Connecting"] = "Verbinde …",
        ["NotConnected"] = "Nicht verbunden",
        ["NoHeadset"] = "Kein Headset",
        ["SearchAgain"] = "Erneut suchen",
        ["Reconnect"] = "Neu verbinden",
        ["Connected"] = "Verbunden",
        ["Charging"] = "lädt",
        ["WornState"] = "aufgesetzt",
        ["NotWornState"] = "abgesetzt",
        ["DisconnectedRetry"] = "Getrennt – nächster Versuch folgt",
        ["Disconnected"] = "Getrennt",
        ["HeadsetDisconnected"] = "MOMENTUM 4 getrennt",
        ["DisconnectedMessage"] = "Headset aus, außer Reichweite oder Bluetooth aus. Die App verbindet sich automatisch wieder.",
        ["BatteryWindows"] = "{0} % (Windows)",
        // Geräte / Aktionen
        ["Connect"] = "Verbinden",
        ["Rename"] = "Umbenennen",
        ["Back"] = "Zurück",
        ["Save"] = "Speichern …",
        ["Clear"] = "Leeren",
        ["Pause"] = "Pause",
        ["OpenApp"] = "App öffnen",
        // Einstellungen
        ["StateOn"] = "Ein",
        ["StateOff"] = "Aus",
        ["Settings"] = "Einstellungen",
        ["General"] = "Allgemein",
        ["Bluetooth"] = "Bluetooth",
        ["Diagnostics"] = "Diagnose",
        ["Advanced"] = "Erweitert",
        ["LanguageLabel"] = "Sprache",
        ["LanguageAuto"] = "Automatisch (Windows)",
        ["LanguageGerman"] = "Deutsch",
        ["LanguageEnglish"] = "English",
        ["LanguageRestartHint"] = "Wird nach einem Neustart der App übernommen.",
        ["UpdatesLabel"] = "Beim Start auf Updates prüfen (fragt GitHub)",
        ["CheckNow"] = "Jetzt prüfen",
        ["UpToDate"] = "Aktuell (Version {0})",
        ["UpdateAvailable"] = "Version {0} verfügbar",
        ["UpdateChecking"] = "Prüfe …",
        ["UpdateFailed"] = "Prüfung nicht möglich (offline?)",
        ["OpenRelease"] = "Release öffnen",
        ["UpdateBalloonTitle"] = "Update verfügbar",
        ["UpdateBalloonBody"] = "MOMENTUM 4 Control {0} ist verfügbar.",
        ["RefreshInterval"] = "Abfrageintervall (Rückfall, falls eine Meldung ausbleibt)",
        ["BatteryInTooltip"] = "Akku im Tray-Tooltip",
        ["StartMinimized"] = "Beim Start nur ins Tray",
        ["StartWithWindows"] = "Mit Windows starten",
        ["RestoreTransparency"] = "Transparenz nach dem Einschalten wiederherstellen",
        ["RestoreTransparencyHint"] = "Das Headset startet immer ohne Transparent Hearing. War vor dem Ausschalten Transparenz aktiv, schaltet die App sie beim Wiederverbinden wieder ein – auch wenn sie zwischendurch an einem anderen Gerät ausgeschaltet wurde.",
        ["ProtocolLogging"] = "Protokoll-Logging",
        ["ProtocolLoggingHint"] = "Schreibt jeden Befehl mit Zeit, Inhalt und Dauer ins Log (rund 10 MB pro Tag). Logs werden nach 14 Tagen gelöscht.",
        ["AnonymizeExport"] = "Beim Export anonymisieren (Adressen, Gerätenamen)",
        ["ExportDiagnostics"] = "Diagnose exportieren …",
        ["OpenLogFolder"] = "Log-Ordner öffnen",
        ["SettingsNotPushedHint"] = "Außer Touch meldet das Headset Änderungen an diesen Einstellungen nicht. Stellst du sie am Handy um, zeigt die App das erst beim nächsten vollständigen Lesen.",
        ["CloseHint"] = "Fenster schließen lässt die App im Tray weiterlaufen; beenden über „Beenden“ im Tray-Menü.",
        // Protokoll-Inspektor (Entwicklungs-Build)
        ["InspectorDev"] = "Protokoll-Inspektor (Entwicklung) …",
        ["InspectorTitle"] = "Protokoll-Inspektor",
        ["ProtocolLog"] = "Protokoll-Log (alle Befehle mit Zeit und Dauer)",
        ["Protocol"] = "Protokoll",
        ["InspectorHint"] = "Nur Anzeige (Entwicklungs-Build). Senden eigener Befehle nur über m4poc mit Policy-Prüfung. ⚑ = Notification.",
        ["ProtocolLine"] = "GAIA v3 über RFCOMM (Vendor 0x0495), nur auf Hardware verifizierte Befehle",
        ["UnofficialSuffix"] = " · inoffiziell, nicht von Sennheiser",
        ["ConnLowerConnected"] = "verbunden",
        ["ConnLowerConnecting"] = "verbinde …",
        ["ConnLowerRetry"] = "getrennt, nächster Versuch folgt",
        ["ConnLowerDisconnected"] = "getrennt",
        ["Setting"] = "Wird gesetzt …",
        ["DeviceNameSetHint"] = "Gesetzt: {0}. In den Windows-Bluetooth-Einstellungen kann der alte Name noch stehen, bis Windows ihn neu liest.",
        ["NotSet"] = "Nicht gesetzt: {0}",
        ["SavedRestart"] = "Gespeichert – gilt ab dem nächsten Start der App.",
        ["AutostartFailed"] = "Autostart konnte nicht geändert werden: {0}",
        ["ZipArchive"] = "ZIP-Archiv",
        ["Exporting"] = "Exportiere …",
        ["Exported"] = "Gespeichert: {0}{1}",
        ["AnonymizedSuffix"] = " (anonymisiert)",
        ["ExportFailed"] = "Export fehlgeschlagen: {0}",
        ["AutostartOn2"] = "Startet dann minimiert im Tray.",
        ["AutostartDisabled"] = "Im Task-Manager unter „Autostart“ deaktiviert – dort wieder aktivieren.",
        ["AutostartPointsElsewhere"] = "Der Eintrag zeigt auf eine andere Programmdatei – aus- und wieder einschalten.",
        ["AutostartActive"] = "Aktiv: startet mit Windows minimiert im Tray.",
        ["AutoOffNever"] = "Nie",
        ["AutoOff15"] = "Nach 15 Minuten",
        ["AutoOff30"] = "Nach 30 Minuten",
        ["AutoOff60"] = "Nach 60 Minuten",
        ["PromptTonesVoice"] = "Töne und Stimme",
        ["PromptTonesOnly"] = "Nur Töne",
        ["PromptOff"] = "Aus",
        ["AutoOffOther"] = "Am Headset eingestellt: {0} – eine andere Stufe als hier.",
        ["ActPrompts"] = "Töne & Sprachansagen „{0}“",
        ["ActAutoOff"] = "Automatisch ausschalten „{0}“",
        ["ThisPc"] = "{0} (dieser PC)",
        ["MultipointHint"] = "{0} von {1} Geräten verbunden. Zum Verbinden erst ein Gerät an diesem Gerät selbst trennen.",
        ["ActConnectPeer"] = "Verbinden mit „{0}“",
        ["ErrNotApplied"] = "vom Headset nicht übernommen – angezeigt wird der tatsächliche Stand.",
        ["ErrNotConnected"] = "Headset nicht verbunden.",
        ["ErrNotAllowed"] = "nicht erlaubt ({0}).",
        ["ErrRejected"] = "vom Headset abgelehnt{0}.",
        ["ErrCode"] = " (Code 0x{0:X2})",
        ["ErrNoResponse"] = "keine Antwort vom Headset.",
        ["InspNoService"] = "Kein Headset-Service – nichts anzuzeigen.",
        ["InspWaiting"] = "Wartet auf Verkehr …",
        ["InspFrames"] = "{0} Frames (neueste oben, höchstens {1})",
        ["InspUnreadable"] = "Frame nicht lesbar",
        ["NoHeadsetProblem"] = "Kein gekoppeltes MOMENTUM 4 gefunden. In den Windows-Bluetooth-Einstellungen koppeln und erneut suchen.",
        ["MultipleHeadsets"] = "{0} MOMENTUM 4 gekoppelt – mehrere Headsets werden noch nicht unterstützt.",
        ["TrayHintTitle"] = "MOMENTUM 4 läuft weiter",
        ["TrayHintBody"] = "Die App ist jetzt nur im Infobereich der Taskleiste. Beenden über das Tray-Menü.",
        ["TrayConnected"] = "MOMENTUM 4 – verbunden",
        ["TrayConnectedBattery"] = "MOMENTUM 4 – {0} %",
        ["ChargingSuffix"] = " (lädt)",
        ["TrayConnecting"] = "MOMENTUM 4 – verbinde …",
        ["TrayNoHeadset"] = "MOMENTUM 4 – kein Headset gefunden",
        ["TrayWindows"] = "MOMENTUM 4 – {0} % (über Windows, Steuerung getrennt)",
        ["TrayDisconnected"] = "MOMENTUM 4 – getrennt",
        ["TrayBattery"] = "Akku: {0} %",
        ["TrayBatteryWindows"] = "Akku: {0} % (Windows) – Steuerung getrennt",
        ["TrayEqPreset"] = "Equalizer-Preset",
        ["Open"] = "Öffnen",
        ["Quit"] = "Beenden",
        ["NotApplied"] = "Nicht ausgeführt",
        ["ActPreset"] = "Preset „{0}“",
    };

    private static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        ["NoiseControl"] = "Noise Control",
        ["Equalizer"] = "Equalizer",
        ["Devices"] = "Devices",
        ["Behavior"] = "Behavior",
        ["Headset"] = "Headset",
        ["Firmware"] = "Firmware",
        ["SerialNumber"] = "Serial number",
        ["DeviceName"] = "Device name",
        ["PromptLanguageLabel"] = "Prompt language",
        ["LastFullRead"] = "Last full read",
        ["AntiWind"] = "Anti-wind",
        ["AncStrength"] = "ANC strength",
        ["SoundMode"] = "Sound mode",
        ["BassBoost"] = "Bass boost",
        ["Preset"] = "Preset",
        ["AutoPauseTransparency"] = "Auto-pause on transparency",
        ["CustomCurvePlaceholder"] = "Custom curve",
        ["CurveName"] = "Name for the current curve",
        ["SaveAsPreset"] = "Save as your own preset",
        ["OnHead"] = "On-head detection",
        ["SmartPause"] = "Smart pause (pause when taken off)",
        ["TouchControls"] = "Touch controls (gestures on the headphone)",
        ["AutoAnswer"] = "Auto-answer calls",
        ["ComfortCall"] = "Comfort call",
        ["Prompts"] = "Tones & voice prompts",
        ["AutoPowerOff"] = "Auto power-off",
        ["ModeTransparency"] = "Transparency",
        ["ModeAnc"] = "ANC",
        ["ModeAdaptive"] = "Adaptive",
        ["ModeOff"] = "Off",
        ["AntiWindOff"] = "Off",
        ["AntiWindMax"] = "Maximum",
        ["AntiWindAuto"] = "Automatic",
        ["HintTransparency"] = "Ambient sound is audible (Transparent Hearing).",
        ["HintCustom"] = "Noise cancelling at a fixed strength.",
        ["HintAdaptive"] = "The headset adapts noise cancelling automatically.",
        ["HintOff"] = "No noise cancelling, only passive isolation.",
        ["ActNoiseControl"] = "Noise Control “{0}”",
        ["ActAntiWind"] = "Anti-wind “{0}”",
        ["ActAutoPauseOn"] = "Auto-pause on",
        ["ActAutoPauseOff"] = "Auto-pause off",
        ["ActAncStrength"] = "ANC strength {0} %",
        ["SearchingHeadset"] = "Searching for MOMENTUM 4 …",
        ["Connecting"] = "Connecting …",
        ["NotConnected"] = "Not connected",
        ["NoHeadset"] = "No headset",
        ["SearchAgain"] = "Search again",
        ["Reconnect"] = "Reconnect",
        ["Connected"] = "Connected",
        ["Charging"] = "charging",
        ["WornState"] = "worn",
        ["NotWornState"] = "off",
        ["DisconnectedRetry"] = "Disconnected — retrying",
        ["Disconnected"] = "Disconnected",
        ["HeadsetDisconnected"] = "MOMENTUM 4 disconnected",
        ["DisconnectedMessage"] = "Headset off, out of range, or Bluetooth off. The app reconnects automatically.",
        ["BatteryWindows"] = "{0} % (Windows)",
        ["Connect"] = "Connect",
        ["Rename"] = "Rename",
        ["Back"] = "Back",
        ["Save"] = "Save …",
        ["Clear"] = "Clear",
        ["Pause"] = "Pause",
        ["OpenApp"] = "Open app",
        ["StateOn"] = "On",
        ["StateOff"] = "Off",
        ["Settings"] = "Settings",
        ["General"] = "General",
        ["Bluetooth"] = "Bluetooth",
        ["Diagnostics"] = "Diagnostics",
        ["Advanced"] = "Advanced",
        ["LanguageLabel"] = "Language",
        ["LanguageAuto"] = "Automatic (Windows)",
        ["LanguageGerman"] = "Deutsch",
        ["LanguageEnglish"] = "English",
        ["LanguageRestartHint"] = "Applied after restarting the app.",
        ["UpdatesLabel"] = "Check for updates on start (asks GitHub)",
        ["CheckNow"] = "Check now",
        ["UpToDate"] = "Up to date (version {0})",
        ["UpdateAvailable"] = "Version {0} available",
        ["UpdateChecking"] = "Checking …",
        ["UpdateFailed"] = "Couldn't check (offline?)",
        ["OpenRelease"] = "Open release",
        ["UpdateBalloonTitle"] = "Update available",
        ["UpdateBalloonBody"] = "MOMENTUM 4 Control {0} is available.",
        ["RefreshInterval"] = "Poll interval (fallback if a notification is missed)",
        ["BatteryInTooltip"] = "Battery in the tray tooltip",
        ["StartMinimized"] = "Start minimized to tray",
        ["StartWithWindows"] = "Start with Windows",
        ["RestoreTransparency"] = "Restore transparency after power-on",
        ["RestoreTransparencyHint"] = "The headset always starts without Transparent Hearing. If transparency was active before power-off, the app turns it back on when reconnecting — even if it was switched off on another device in the meantime.",
        ["ProtocolLogging"] = "Protocol logging",
        ["ProtocolLoggingHint"] = "Writes every command with time, content and duration to the log (about 10 MB per day). Logs are pruned after 14 days.",
        ["AnonymizeExport"] = "Anonymize on export (addresses, device names)",
        ["ExportDiagnostics"] = "Export diagnostics …",
        ["OpenLogFolder"] = "Open log folder",
        ["SettingsNotPushedHint"] = "Except for touch, the headset does not report changes to these settings. If you change them on your phone, the app shows it only on the next full read.",
        ["CloseHint"] = "Closing the window keeps the app running in the tray; quit via “Quit” in the tray menu.",
        ["InspectorDev"] = "Protocol inspector (dev) …",
        ["InspectorTitle"] = "Protocol inspector",
        ["ProtocolLog"] = "Protocol log (all commands with time and duration)",
        ["Protocol"] = "Protocol",
        ["InspectorHint"] = "Display only (dev build). Send your own commands only via m4poc with policy checks. ⚑ = notification.",
        ["ProtocolLine"] = "GAIA v3 over RFCOMM (vendor 0x0495), only hardware-verified commands",
        ["UnofficialSuffix"] = " · unofficial, not from Sennheiser",
        ["ConnLowerConnected"] = "connected",
        ["ConnLowerConnecting"] = "connecting …",
        ["ConnLowerRetry"] = "disconnected, retrying",
        ["ConnLowerDisconnected"] = "disconnected",
        ["Setting"] = "Setting …",
        ["DeviceNameSetHint"] = "Set: {0}. Windows Bluetooth settings may still show the old name until Windows re-reads it.",
        ["NotSet"] = "Not set: {0}",
        ["SavedRestart"] = "Saved — applies after the next app start.",
        ["AutostartFailed"] = "Could not change autostart: {0}",
        ["ZipArchive"] = "ZIP archive",
        ["Exporting"] = "Exporting …",
        ["Exported"] = "Saved: {0}{1}",
        ["AnonymizedSuffix"] = " (anonymized)",
        ["ExportFailed"] = "Export failed: {0}",
        ["AutostartOn2"] = "Then starts minimized in the tray.",
        ["AutostartDisabled"] = "Disabled in Task Manager under \u201cStartup\u201d — re-enable it there.",
        ["AutostartPointsElsewhere"] = "The entry points at a different executable — turn it off and on again.",
        ["AutostartActive"] = "Active: starts with Windows, minimized in the tray.",
        ["AutoOffNever"] = "Never",
        ["AutoOff15"] = "After 15 minutes",
        ["AutoOff30"] = "After 30 minutes",
        ["AutoOff60"] = "After 60 minutes",
        ["PromptTonesVoice"] = "Tones and voice",
        ["PromptTonesOnly"] = "Tones only",
        ["PromptOff"] = "Off",
        ["AutoOffOther"] = "Set on the headset: {0} — a different level than here.",
        ["ActPrompts"] = "Tones & voice prompts \u201c{0}\u201d",
        ["ActAutoOff"] = "Auto power-off \u201c{0}\u201d",
        ["ThisPc"] = "{0} (this PC)",
        ["MultipointHint"] = "{0} of {1} devices connected. To connect another, first disconnect one on the device itself.",
        ["ActConnectPeer"] = "Connect to \u201c{0}\u201d",
        ["ErrNotApplied"] = "not accepted by the headset — the actual state is shown.",
        ["ErrNotConnected"] = "headset not connected.",
        ["ErrNotAllowed"] = "not allowed ({0}).",
        ["ErrRejected"] = "rejected by the headset{0}.",
        ["ErrCode"] = " (code 0x{0:X2})",
        ["ErrNoResponse"] = "no response from the headset.",
        ["InspNoService"] = "No headset service — nothing to show.",
        ["InspWaiting"] = "Waiting for traffic …",
        ["InspFrames"] = "{0} frames (newest on top, at most {1})",
        ["InspUnreadable"] = "frame unreadable",
        ["NoHeadsetProblem"] = "No paired MOMENTUM 4 found. Pair it in Windows' Bluetooth settings and search again.",
        ["MultipleHeadsets"] = "{0} MOMENTUM 4 paired — multiple headsets are not supported yet.",
        ["TrayHintTitle"] = "MOMENTUM 4 keeps running",
        ["TrayHintBody"] = "The app is now only in the notification area. Quit via the tray menu.",
        ["TrayConnected"] = "MOMENTUM 4 — connected",
        ["TrayConnectedBattery"] = "MOMENTUM 4 — {0} %",
        ["ChargingSuffix"] = " (charging)",
        ["TrayConnecting"] = "MOMENTUM 4 — connecting …",
        ["TrayNoHeadset"] = "MOMENTUM 4 — no headset found",
        ["TrayWindows"] = "MOMENTUM 4 — {0} % (via Windows, control disconnected)",
        ["TrayDisconnected"] = "MOMENTUM 4 — disconnected",
        ["TrayBattery"] = "Battery: {0} %",
        ["TrayBatteryWindows"] = "Battery: {0} % (Windows) — control disconnected",
        ["TrayEqPreset"] = "Equalizer preset",
        ["Open"] = "Open",
        ["Quit"] = "Quit",
        ["NotApplied"] = "Not applied",
        ["ActPreset"] = "Preset \u201c{0}\u201d",
    };
}
